### ISSUE TITLE
Invalid yaml

### ISSUE THREAD

**Issue by twiecki** [conda-forge/pytensor-suite-feedstock#8]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

https://github.com/conda-forge/pytensor-suite-feedstock/blob/dab6667bd5e8ba1c43744c162358e05f78ffb033/conda-forge.yml#L6-L7 seems to be wrong as per Chris Burr on gitter

### Installed packages

```shell
asdf
```

### Environment info

```shell
asdf
```

**Comment by maresb** [comment]
@michaelosthege

**Comment by maresb** [comment]
Ya, it's invalid at the level of a data structure. Yaml is just like json, so you have here a dict with duplicate keys.

**Comment by maresb** [comment]
Can u link Chris 's message or was it private. Somehow I am not finding it. Does he suspect that this is leading to any problems? I would expect the second pkgformat to simply override the first.

**Comment by twiecki** [comment]
It's in the thread 
<img width="426" alt="image" src="https://user-images.githubusercontent.com/674200/208780504-86629b01-7c10-4af7-8a24-036283bb782a.png">
doesn't seem like I can link

**Comment by michaelosthege** [comment]
Yeah, looks like I misread the documentation ... and because YAML.

We should fix it in all three feedstocks:
* https://github.com/conda-forge/pytensor-suite-feedstock/blob/main/conda-forge.yml
* https://github.com/conda-forge/pymc-feedstock/blob/main/conda-forge.yml
* https://github.com/conda-forge/sunode-feedstock/blob/main/conda-forge.yml

We could even stop releasing `.tar.bz2` again, because it looked like the installation problems that motivated me to make that change in the first place were actually just a consequence of my slightly outdated `conda/mamba` running in a Python 3.7 base environment.

**Comment by michaelosthege** [comment]
I opened PRs in all three feedstocks.

On sunode only Adrian and I are set as maintainers, but for PyTensor and PyMC feedstocks either of you can approve/merge them.
